### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by jqtrde** [Code4Maine/code4maine.github.com#1]
At this point, seems like the next thing we need is some content. @Cribstone if you could post those wireframes up I can start filling in the site!

**Comment by Cribstone** [comment]
Awesome!  Thank you again!  I just have a few tweaks that I would've done this morning if I didn't get distracted by a new robotics project...  I'm on it now though:)

**Comment by Cribstone** [comment]
My only problem now is that I used a LibreOffice wire framing template and rather than make it easy to upload to GoogleDrive they use some sort of system called CMIS for cloud storage...  I guess I signed up for this when taking the oath of Linux but jeez... Should be a little easier you'd think

**Comment by janewilkin** [comment]
Just email it to us and we can put it in github.  

## 

Garrett Wilkin
207 505 2482
http://about.me/garrettwilkin
http://www.programmableweb.com/profile/garrettwilkin

**Comment by jqtrde** [comment]
Haha, no worries. I'm running Archlinux, so I have LibreOffice too. You can
just email them to me directly if that would be easier.

On Mon, Mar 25, 2013 at 2:01 PM, Andrew Jawitz notifications@github.comwrote:

> My only problem now is that I used a LibreOffice wire framing template and
> rather than make it easy to upload to GoogleDrive they use some sort of
> system called CMIS for cloud storage... I guess I signed up for this when
> taking the oath of Linux but jeez... Should be a little easier you'd think
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Code4Maine/code4maine.github.com/issues/1#issuecomment-15409967
> .

## 

Jacques http://jacquestardie.org/ (207) 460-2865

**Comment by Cribstone** [comment]
Can you open .odp docs?  Its not fully finished but I figured it would get
us started...

**Comment by jqtrde** [comment]
Yep

On Mon, Mar 25, 2013 at 2:06 PM, Andrew Jawitz notifications@github.comwrote:

> Can you open .odp docs? Its not fully finished but I figured it would get
> us started...
> On Mar 25, 2013 2:04 PM, "Garrett Wilkin" notifications@github.com
> wrote:
> 
> > Just email it to us and we can put it in github.
> > 
> > ## 
> > 
> > Garrett Wilkin
> > 207 505 2482
> > http://about.me/garrettwilkin
> > http://www.programmableweb.com/profile/garrettwilkin
> > 
> > On Monday, March 25, 2013 at 2:01 PM, Andrew Jawitz wrote:
> > 
> > > My only problem now is that I used a LibreOffice wire framing template
> > > and rather than make it easy to upload to GoogleDrive they use some sort
> > > of
> > > system called CMIS for cloud storage... I guess I signed up for this
> > > when
> > > taking the oath of Linux but jeez... Should be a little easier you'd
> > > think
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub (
> > 
> > https://github.com/Code4Maine/code4maine.github.com/issues/1#issuecomment-15409967).
> > 
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/Code4Maine/code4maine.github.com/issues/1#issuecomment-15410194>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Code4Maine/code4maine.github.com/issues/1#issuecomment-15410309
> .

## 

Jacques http://jacquestardie.org/ (207) 460-2865

**Comment by Cribstone** [comment]
Is it better to scale a .png file down if its larger than you need than to try to use a small file for a big picture?  Or does it lose resolution either way?  In other words, would it make it easier if I upload .png's at 100 x 100px rather than 64 in case you need a larger icon?

**Comment by jqtrde** [comment]
I'd upload at the largest possible size.

On Wed, Mar 27, 2013 at 5:59 PM, Andrew Jawitz notifications@github.comwrote:

> Is it better to scale a .png file down if its larger than you need than to
> try to use a small file for a big picture? Or does it lose resolution
> either way? In other words, would it make it easier if I upload .png's at
> 100 x 100px rather than 64 in case you need a larger icon?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Code4Maine/code4maine.github.com/issues/1#issuecomment-15555841
> .

## 

Jacques http://jacquestardie.org/ (207) 460-2865
