### ISSUE TITLE
Creating New Projects out of multiple repos

### ISSUE THREAD

**Issue by Cribstone** [Code4Maine/code4maine.github.com#4]
Under the "Workshop" section I would like to display our projects as direct links to their respective repo's on our Github page.  The question I have is how we can take multiple repo's we forked from other places and merge them into a new project, while still maintaining their original file structure.
   For example, for our Public Document Scanning project I forked two different Repo's.  One  is forked from the DIYBookScanner project- https://github.com/Code4Maine/diybookscanner and the other is forked from an Open Source OCR app- https://github.com/Code4Maine/dochive.  Now how do I go about merging both Repo's into a new project called "Public Document Digitization" (or something) without having to merge the DIYBookScanner repo which basically just includes hardware assembly instructions with Dochive which is software source code?

**Comment by jqtrde** [comment]
@Cribstone You should check this out: http://www.codeschool.com/courses/try-git. It's a nice intro to Git that I think you'll appreciate.

**Comment by Cribstone** [comment]
OK...  Did the tutorial, and while it didn't really answer my question, it did possibly teach me how to make sense when I'm asking it.  So I'll give it another shot...
  Here's the scenario-  I want to create a project that enables public documents, libraries, archives etc... to be scanned into a searchable format.  So let's say I create a new repo named "The Open Document Project".  Now the "ODP" will involve two different components, one will be the physical scanning of the documents using the diybookscanner.org build.  The next component will be to convert the scanned documents from a raw PDF into a searchable format using an open source OCR app called "Dochive".  
   The first part is easy because both the book scanner (git://github.com/markvdb/diybookscanner.git) and Dochive (git://github.com/raleighpublicrecord/dochive.git) have their own Github Repo's.  So I forked both of them and now I have two seperate Repo's- https://github.com/Code4Maine/dochive and https://github.com/Code4Maine/diybookscanner.  
   What I really want to do is have both as sub repositories under the "Open Document Project" umbrella so they would each look like this-
  github.com/Code4Maine/opendocproject/diybookscanner AND github.com/Code4Maine/opendocproject/dochive
  Along with a wiki page and perhaps a Landing Page.
What I don't want to do is merge them so all of their individual files get mixed up in the same directory.
  I tried to do this before with another project before Code4Maine called "CarFree Maine".  I wanted to collect all the open source transit-related projects on Github into one place, so when I asked other brigade captains for suggestions they advised that I create a new repo for a wiki page, which I did- https://github.com/carfreemaine/opentransitwiki/wiki and then add the other projects to the Wiki page.  But all this did was create an HTML wiki with hyperlinks to the repo's which I couldve just done with Wikispaces or whatever...  I want to be able to fork multiple repos from outside our organization and put them all together under one roof.
   Am I making sense?

**Comment by jqtrde** [comment]
@Cribstone,

I think what you're looking for are [Submodules](http://git-scm.com/book/en/Git-Tools-Submodules).

Before you start, make sure that you actually do need to Fork these projects. When you fork a project, you're starting a separate development branch. Are you planning on adding features to these pre-existing projects, or are you just using them as is. If it's the latter, then I'm not sure that you need to fork them, as opposed to just linking to them.

Hope that helps,

**Comment by jqtrde** [comment]
Guessing that this has been resolved...
