### ISSUE TITLE
Merging content from Brigade Templates into index.html

### ISSUE THREAD

**Issue by Cribstone** [Code4Maine/code4maine.github.com#5]
So you guys might've noticed me fumbling around with the branch editing feature over the past week.  For the most part, I was having trouble setting up a local workspace but I eventually got around this by setting up a cloud9 workspace. This workspace should be accessible to team-members if you go to https://c9.io/cribstone/code4maine_github_com and request access.  We can even code in real-time!
   I managed to edit the main index.html file and added the basic copy.  Now my biggest issue is how to add links and images akin to the standard brigade template at https://github.com/c4hrva/c4hrva-landing
  When I compare the index files from both templates side by side there are significant differences and I'm not sure if they were based on different bootstrap templates to begin with or if I just need to make a few minor changes.
   Can you do me a favor and take a look at either https://github.com/c4hrva/c4hrva-landing or https://github.com/codeforsandiego/codeforsandiego.github.com and let me know if I'm missing anything?

**Comment by jqtrde** [comment]
Sure thing @Cribstone, I'll get on that later this afternoon!

**Comment by Cribstone** [comment]
I'm not sure if you were able to take a look at this issue but I cloned this project into a workspace on Cloud9 IDE- https://c9.io/cribstone/code4maine_github_com which you should be able to access.  Garrett and I tested it out last week and all you have to do is submit a request and once I approve it you'll be able to make any changes online.
   I don't know if this will make things easier, but I thought I would mention it.  We can also use the chat dialog to communicate in real-time if we wanted to do it that way.

**Comment by jqtrde** [comment]
@Cribstone Just requested permission. I'm new to C9, do you like it more than Github's built in editors?

**Comment by jqtrde** [comment]
Copied Code4SanDiego's page an rebranded it with Maine where appropriate. _I think._

[The site](http://code4maine.github.io/) is live.

@Cribstone, to set this up locally:
1. clone `https://github.com/Code4Maine/code4maine.github.com.git`
2. install jekyll `gem install jekyll` more details [here](http://jekyllrb.com/)
3. 'jekyll serve --watch'

That said, I'd just use Github's native editing tools and push to `master` via the web-interface. We can always roll back to previous commits if something happens, and the deployment process will essentially become nonexistant.

Let me know what you think.

**Comment by Cribstone** [comment]
Just gave you RW permissions so you should be able to add commit and push changes to anything. To be honest, I totally forgot gh even had a built-in editor! Even then, the only one I ever tried to work with was prose.io, so there might be much I don't even know about.
   Cloud9 is mostly useful for the team collaboration features and because its based on node.js, it can be used to program embedded applications (as it does with the Beagelbone Black, which is how I started using the IDE).  Seeing as remote collaboration workspaces are going to be especially important for us in Maine, this feature is potentially a game changer.  In at least one example I'm thinking of combining it with some kind of open source videoconferencing platform and Github to encourage an online hack-a-thon.  
   That said, as something based on node.js, it clearly has some bugs to work out. Thus far, if I'm looking for some powercoding tools, I'll stick to my Sublime Text for now...

**Comment by jqtrde** [comment]
@Cribstone you should check these posts out: [Github Flow in the Browser](https://github.com/blog/1557-github-flow-in-the-browser) & [Edit like an Ace](https://github.com/blog/905-edit-like-an-ace).

I think for the purposes of this repository at least, it'll make life easier for you.

**Comment by Cribstone** [comment]
HA that was fast!
  It looks good. Yeah, when I was going over the SD Code, I was surprised at how little I really had to change.  The big blocker for me was the background image, and links to things that we might have but SD Doesn't (or vice versa).
   So while San Diego links to their discussion group, we have multiple discussion forums might want to link to.  Plus we need somewhere to add all the Maine Hacker Club links and a group calendar...

**Comment by Cribstone** [comment]
You should be able to leave comments on Cloud9 BTW...  So if you get the chance it would be awesome if you could highlight the areas where the link URLs go and also show me where to drop the background images that would be perfect!

**Comment by jqtrde** [comment]
the background image is located [here](https://github.com/Code4Maine/code4maine.github.com/blob/master/index.html#L112).

You can edit the index.html by going [here](https://github.com/Code4Maine/code4maine.github.com/edit/master/index.html)

**Comment by Cribstone** [comment]
Fantastic! Looks Great Jacques!

**Comment by jqtrde** [comment]
Going to close this since I think this particular issue has been addressed.
