### ISSUE TITLE
Domain registration

### ISSUE THREAD

**Issue by jqtrde** [Code4Maine/code4maine.github.com#6]
Currently, accessing the page means heading to [http://code4maine.github.io/](http://code4maine.github.io/). Thoughts on registering a new domain name? `codeformaine.org`?

**Comment by jqtrde** [comment]
`codeformaine.org` is unavailable. `code4maine.org` is available.

**Comment by Cribstone** [comment]
I actually prefer code4maine.  Hence the repo URL...  I think CfA can
provide free hosting.  If they can't just provide it directly, I know they
can reimburse.
   What do you use for hosting usually?

http://about.me/ajawitz

**Comment by jqtrde** [comment]
[gandi](http://gandi.net) or [dnsimple](http://dnsimple.com)

i'll register it tonight, if you could figure out the reimbursement schiz that would be fantastic.

**Comment by Cribstone** [comment]
Jacques-
   Check your email for an invite to a Google Group with a CfA URL.  The invite should explain why it is relevant to setting up hosting accounts etc..  Do let me know if you don't get it or can't access it.

**Comment by jqtrde** [comment]
Got it. Didn't get a chance to register the domain last night though...

**Comment by jqtrde** [comment]
[code4maine.org](http://code4maine.org/)
