### ISSUE TITLE
Adding a Hacker Directory

### ISSUE THREAD

**Issue by Cribstone** [Code4Maine/code4maine.github.com#7]
So I just noticed that one of the repos I forked over to Code4Maine now has the URL for the domain- http://code4maine.org/opentransitprojects/ 
   Does this mean all of our current Repo's will have a subheading on our new webpage?  Thats fine by me, but I was wondering how we should proceed with adding a new directory for all the other hacker groups (i.e Hacker Club, Hack Portland, Maine Fablab etc...).  Does it make sense to create a new repo and a wiki using gh pages markup? 
   Also we set up a group calendar at codeforamerica.org_09jjhoqlt2vrkh6r3ne8ko3flc@group.calendar.google.com
   It includes html for embedding into blogs etc...

**Comment by jqtrde** [comment]
Every repo that also has a gh-pages branch will have a subdirectory at [code4maine.github.io](http://code4maine.github.io), thanks to Github functionality.

Since we've added a [CNAME](https://github.com/Code4Maine/code4maine.github.com/blob/master/CNAME) that points [code4maine.github.io](http://code4maine.github.io) to [code4maine.org](http://code4maine.org), this will apply to that domain as well.

**Comment by jqtrde** [comment]
I don't think creating repo's would be the best way here. Instead, I'll add CNAME records to our DNSimple that will point those links to the hacker clubs to the appropriate urls.

**Comment by jqtrde** [comment]
Lastly, could you send me an invite to that Calendar. [hi@jacquestardie.org](hi@jacquestardie.org) please :)

**Comment by Cribstone** [comment]
Name Added to Calendar, R/W Access

**Comment by jqtrde** [comment]
Thanks!

**Comment by Cribstone** [comment]
RE- "I don't think creating repo's would be the best way here. Instead, I'll add CNAME records to our DNSimple that will point those links to the hacker clubs to the appropriate urls."

That list of links might start to get kind of long wouldn't it? I didn't mean to create a new repo for each group, I meant to create a wiki via gh-pages to serve as one directory where people from all the various cities can add and update their information rather than having it all on the landing page, which is intended to be more of an introducion anyway. What I'm confused about is how the wiki function that comes with every individual repo works. In the case of code4maine.github.io it would be here- https://github.com/Code4Maine/code4maine.github.com/wiki

In the case, of the page under the URL- http://code4maine.org/opentransitprojects/ I just used the standard wiki function in the repo and added gh-pages to it.

So this is what I was thinking of doing for a new hacker directory. For the most part the benefit of doing it this way would be the ease of adding new information. If I want to add or change a new group or link, I can just add it directly to the markdown editor, click save and I'm done. Do you see what I mean?

**Comment by Cribstone** [comment]
I think we've moved the discussion on from this issue.  But I have one last request before we close...  Where in the index.html do I add links to new highlighted projects?  Right now it would be underneath the section with the link to the OpenVehicleTracker.  Right now there's code4maine.org/opentransitprojects, code4maine.org/papermachine and possibly code4maine.org/mainewiki which would be the hacker directory.  However, we might want to put that page in a more prominent location so it invites more participation from non- civic hackers.
  There's also an adopt-a-sidewalk project coming up in Bath and Sam in Portland has been moving forward with the Adopt-A-Buttler project.

**Comment by jqtrde** [comment]
Agreed, these projects should be featured more prominently than they currently are. Let's figure out where, and how they should be displayed.

The link to the OVT is at [https://github.com/Code4Maine/code4maine.github.com/blob/master/index.html#L203-L205](https://github.com/Code4Maine/code4maine.github.com/blob/master/index.html#L203-L205). New additions would be appended after.
