### ISSUE TITLE
Octopress?

### ISSUE THREAD

**Issue by Cribstone** [Code4Maine/code4maine.github.com#8]
It has become clear lately that one of the most important roles we can play through Code for Maine is to connect the various fragmented hacker groups,universities, fablabs, governments, startups etc... around the state.  We possibly have more capability in this regard because of the Code for America brand.  
   With that in mind, we've been discussing the need for a more robust platform that we can use to facilitate these connections.  Initially, I had in mind a simple wiki created with gh-pages which would function as a subpage link from our landing page.  
I already had an empty repo called "mainewiki" https://github.com/Code4Maine/mainewiki that I set up for a similar purpose a long time ago but never got around to deploying.  I figured we could use this as our basic template and use the repo's "wiki" feature to easily add content via gh-markdown.- https://github.com/Code4Maine/mainewiki/wiki
   But in the course of trying to find a way to embed our google calendar, I came across Octopress- http://github.com/imathis/octopress.  It is described as an "an obsessively designed framework for Jekyll blogging. "  
   Does this seem like something we could implement?  If so, should I forget about using "mainewiki" and create an entirely new repo based on a fork from Octopress?  Or is there a way to copy over the Octopress files over to what I've already done?

**Comment by jqtrde** [comment]
Octopress is essentially a well-developed Jekyll theme. We could certainly use it here. I'm not sure that we would have any need to fork Octopress, but it would be easy enough to use it on any of or repositories.

I'm a little unclear on how you're envisioning this would work; if you could sketch out a wireframe, that would definitely help me out!

**Comment by Cribstone** [comment]
If you can't quite picture how it might work, it may be because I have only the slightest idea myself:)  I can however, give a little more explanation about why I think such a feature would be needed, and maybe you could give us some input on how best to meet those needs.  
   As it stands now, there still isn't one single place on the web, where Maine hackers, makers, civic techies etc... can go to for information pertaining to the state as a whole.  If I want to post an announcement about the upcoming Open Source Hardware Summit, for example, I have to post it on at least five different message boards, plus Facebook, IRC, Tumblr and Google+...  Just in the last week, we discovered that UMaine has had a publicly accessible FabLab open the entire time we've been talking about setting up a civic makerspace, and things like that keep popping up right under our noses every day.
    There have probably been at least 20 organizations (e.g REALIZEMAINE!, ProjectLogin, TECHMaine, Maine Technology Institute etc...) over the past few years who have tried with little success to connect all the fragmented groups around the state, but for the first time we (as in Code for Maine) have a national brand to focus all the attention.  This is how even I found out about Maine Hacker Club, for example, because Garrett contacted Code for America about NDoCH.
     So at the very basic level we need something like a bulletin board/calendar along with a list of all the various hack nights, fablabs, groups etc... in Maine. With links to their primary website and social media.  
    Since the Brigade Landing page is meant to introduce people to Code for Maine, first and foremost, it wouldn't make much sense to add all this information onto the same page.  Also, we would want to make it simple enough for somebody to add in their own listing without having to mess with our index.html file.
   So I figured we would just link to a new page in a wiki format that would be easy enough for anyone to edit and add new information as it comes in.  This is precisely what I was doing with https://github.com/Code4Maine/mainewiki/wiki until I remembered that we wanted to embed the Google Calendar into it too...  So in the process of looking up how to embed a G-Calendar into markdown.gh text, I discovered how in Octopress they have the capability to add a GCalendar as a Wordpress-style plugin.  My idea was that with such a framework, we would not only have an easy template for adding the current content, but also one that gives us any number of options to choose from in the future.  So if we wanted to add a banner for a statewide unconference, for example, we could find a plugin to do it relatively easily...  https://github.com/imathis/octopress/wiki/3rd-party-plugins
   As far as what these features would look like in the future, I have no idea... Rather I'm looking for something that gives us the flexibility, and accessibility to build out later if we need it.

```
Does that make sense?
```

**Comment by Cribstone** [comment]
I think I've more or less figured out how Jekyll and Octopress works with gh-pages now.  My previous experience with gh-pages was limited to using their automatic page generator, so it took me a little while to learn the language.  
  Thats all the more reason why I'm thinking that Octopress may be the way to go for a hacker directory as it would ideally involve more than just two or three of us adding content and making changes all the time.  Something with the plugin-style modularity of Wordpress combined with the distributed structure of Github seems like the perfect fit for this particular project.  Unless you can think of anything better that meets the goals I outlined earlier?
    Its true that I we really need right now is somewhere to create listings for various groups and a place to embed a Google Calendar.  But as long as it doesn't make things way too complicated, we might as well set up a framework that allows us to add new features as things pick up.

**Comment by jqtrde** [comment]
Agreed, Octopress seems like a good fit.

**Comment by jqtrde** [comment]
Seems like this discussion belongs in the maine-wiki repo, so closing this.
